apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - rabbitmq.yaml
  - order-service.yaml
  - inventory-service.yaml
  - payment-service.yaml

commonLabels:
  project: thesis
  environment: base

configMapGenerator:
  - name: service-config
    literals:
      - LOG_LEVEL=INFO
      - ENVIRONMENT=base