server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            max-age: 3600

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      httpclient:
        connect-timeout: 3000
        response-timeout: 10s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

resilience4j:
  circuitbreaker:
    configs:
      default: 
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
    instances:
      orderServiceCircuitBreaker:
        base-config: default
      paymentServiceCircuitBreaker:
        base-config: default
      inventoryServiceCircuitBreaker:
        base-config: default
      notificationServiceCircuitBreaker:
        base-config: default
        failure-rate-threshold: 60

  timelimiter:
    configs:
      default:
        timeout-duration: 10s
    instances:
      orderServiceCircuitBreaker:
        timeout-duration: 10s
      paymentServiceCircuitBreaker:
        timeout-duration: 5s
      inventoryServiceCircuitBreaker:
        timeout-duration: 5s
      notificationServiceCircuitBreaker:
        timeout-duration: 3s

logging:
  level:
    '[com.tolerant.api_gateway]': INFO
    '[org.springframework.cloud.gateway]': INFO
    '[org.springframework.web]': INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    tags: 
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        '[http.server.requests]': true
      
    
